// File generated by FlutterFire CLI.
// Run `flutterfire configure` to replace placeholder values with your Firebase project config.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzNaPUw1XgAwmqQEecLzQc5yG1vBHgFJo',
    appId: '1:392873674558:web:ab01d6eb252b1c60bb0e6f',
    messagingSenderId: '392873674558',
    projectId: 'home-inventory-manager-4828a',
    authDomain: 'home-inventory-manager-4828a.firebaseapp.com',
    storageBucket: 'home-inventory-manager-4828a.firebasestorage.app',
    measurementId: 'G-5DG6QWWZMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1rmfXBrGkGnsLxZPyoe1yK0smUf6lrc',
    appId: '1:392873674558:android:bfe4917ea7e01d28bb0e6f',
    messagingSenderId: '392873674558',
    projectId: 'home-inventory-manager-4828a',
    storageBucket: 'home-inventory-manager-4828a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP-pWhkfbjIx1gLBrH1qnpZTcL8ruKDx0',
    appId: '1:392873674558:ios:278e98cea9d83483bb0e6f',
    messagingSenderId: '392873674558',
    projectId: 'home-inventory-manager-4828a',
    storageBucket: 'home-inventory-manager-4828a.firebasestorage.app',
    iosBundleId: 'com.example.homeInventoryManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP-pWhkfbjIx1gLBrH1qnpZTcL8ruKDx0',
    appId: '1:392873674558:ios:278e98cea9d83483bb0e6f',
    messagingSenderId: '392873674558',
    projectId: 'home-inventory-manager-4828a',
    storageBucket: 'home-inventory-manager-4828a.firebasestorage.app',
    iosBundleId: 'com.example.homeInventoryManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzNaPUw1XgAwmqQEecLzQc5yG1vBHgFJo',
    appId: '1:392873674558:web:34b3e62598473556bb0e6f',
    messagingSenderId: '392873674558',
    projectId: 'home-inventory-manager-4828a',
    authDomain: 'home-inventory-manager-4828a.firebaseapp.com',
    storageBucket: 'home-inventory-manager-4828a.firebasestorage.app',
    measurementId: 'G-LJ2QHY6XW8',
  );
}
